### 1. Gradient descent learning with multiple inputs

In [101]:
import numpy as np
import numpy.typing as npt

def neural_network(inp: npt.NDArray, weight: npt.NDArray) -> float:
    return inp.dot(weight)

weights = np.array([0.1, 0.2, -0.1])

# Set the inputs
toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

# Set the outputs
win_or_lose_binary = np.array([1, 1, 0, 1])

alpha = 0.005
data_point = 0
goal = win_or_lose_binary[data_point]
inp = np.array([toes[data_point], wlrec[data_point], nfans[data_point]])

# Form a prediction and update weights several times
for iter in range(3):
    pred = neural_network(inp, weights)
    error = (pred - goal) ** 2
    derror = 2 * inp * (pred - goal)

    weights = weights - alpha * derror

    print(f'Iteration: {iter}')
    print(f'Pred: {pred}')
    print(f'Error: {error}')
    print(f'Delta: {pred - goal}')
    print(f'Weights: {weights}')
    print(f'Weight Deltas: {alpha * derror}')

Iteration: 0
Pred: 0.8600000000000001
Error: 0.01959999999999997
Delta: -0.1399999999999999
Weights: [ 0.1119   0.20091 -0.09832]
Weight Deltas: [-0.0119  -0.00091 -0.00168]
Iteration: 1
Pred: 0.9637574999999999
Error: 0.0013135188062500048
Delta: -0.036242500000000066
Weights: [ 0.11498061  0.20114558 -0.09788509]
Weight Deltas: [-0.00308061 -0.00023558 -0.00043491]
Iteration: 2
Pred: 0.9906177228125002
Error: 8.802712522307997e-05
Delta: -0.009382277187499843
Weights: [ 0.11577811  0.20120656 -0.0977725 ]
Weight Deltas: [-7.97493561e-04 -6.09848017e-05 -1.12587326e-04]


### 2. Gradient descent learning with multiple inputs -- one weight is frozen

In [102]:
weights = np.array([0.1, 0.2, -0.1])

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

win_or_lose_binary = np.array([1, 1, 0, 1])

alpha = 0.005
data_point = 0
goal = win_or_lose_binary[data_point]
inp = np.array([toes[data_point], wlrec[data_point], nfans[data_point]])

for iter in range(3):
    pred = neural_network(inp, weights)
    error = (pred - goal) ** 2
    derror = 2 * inp * (pred - goal)
    # Set the first weight to zero so it doesn't participate in learning
    derror[0] = 0

    weights = weights - alpha * derror

    print(f'Iteration: {iter}')
    print(f'Pred: {pred}')
    print(f'Error: {error}')
    print(f'Delta: {pred - goal}')
    print(f'Weights: {weights}')
    print(f'Weight Deltas: {alpha * derror}')

Iteration: 0
Pred: 0.8600000000000001
Error: 0.01959999999999997
Delta: -0.1399999999999999
Weights: [ 0.1      0.20091 -0.09832]
Weight Deltas: [ 0.      -0.00091 -0.00168]
Iteration: 1
Pred: 0.8626075000000001
Error: 0.018876699056249977
Delta: -0.13739249999999992
Weights: [ 0.1         0.20180305 -0.09667129]
Weight Deltas: [ 0.         -0.00089305 -0.00164871]
Iteration: 2
Pred: 0.8651664353125001
Error: 0.018180090166338207
Delta: -0.13483356468749985
Weights: [ 0.1         0.20267947 -0.09505329]
Weight Deltas: [ 0.         -0.00087642 -0.001618  ]


The first weight here doesn't participate in learning process,
but the network still attempts to adjust second and third weights to
minimize the error. This opens up an important property of neural networks --
if the network figures out how to do accurate (enough) prediction
without taking into account a certain weight it may never utilize it
for future predictions.

### 3. Gradient descent learning with multiple outputs

In [103]:
def neural_network(inp: float, weight: npt.NDArray) -> npt.NDArray:
    return inp * weight

weights = np.array([0.3, 0.2, 0.9])

wlrec = np.array([0.65, 0.8, 0.8, 0.9])

hurt = np.array([0.1, 0.0, 0.0, 0.1])
win = np.array([1, 1, 1, 1])
sad = np.array([0.1, 0.0, 0.1, 0.2])

data_point = 0
inp = wlrec[data_point]
goal = np.array([hurt[data_point], win[data_point], sad[data_point]])

alpha = 0.1

for iter in range(2):
    pred = neural_network(inp, weights)
    error = (pred - goal) ** 2
    derror = inp * (pred - goal)

    weights = weights - alpha * derror

    print(f'Iter: {iter}')
    print(f'Error: {error}')
    print(f'Weights: {weights}')
    print(f'Weight Deltas: {derror}')

Iter: 0
Error: [0.009025 0.7569   0.235225]
Weights: [0.293825 0.25655  0.868475]
Weight Deltas: [ 0.06175 -0.5655   0.31525]
Iter: 1
Error: [0.0082785  0.69429306 0.21576838]
Weights: [0.28791089 0.31071076 0.83828193]
Weight Deltas: [ 0.05914106 -0.54160763  0.30193069]


### 4. Gradient descent learning with multiple inputs and outputs


In [113]:
def neural_network(inp: npt.NDArray, weight : npt.NDArray) -> npt.NDArray:
    return inp.dot(weight.T)

weights = np.array([[0.1, 0.1, -0.3], # hurt?
                    [0.1, 0.2, 0.0],  # win?
                    [0.0, 1.3, 0.1]]) # sad?

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

hurt = np.array([0.1, 0.0, 0.0, 0.1])
win = np.array([1, 1, 0, 1])
sad = np.array([0.1, 0.0, 0.1, 0.2])

alpha = 0.01

data_point = 0
inp = np.array([toes[data_point], wlrec[data_point], nfans[data_point]])
goal = np.array([hurt[data_point], win[data_point], sad[data_point]])

for iter in range(3):
    pred = neural_network(inp, weights)
    error = (pred - goal) ** 2
    # The order is reversed in order to create properly transposed matrix
    derror = np.outer((pred - goal), inp)

    weights = weights - alpha * derror

    print(f'Iter: {iter}')
    print(f'Prediction: {pred}')
    print(f'Error: {error}')
    print(f'Delta: {pred - goal}')
    print(f'Weights: {weights}')
    print(f'Weight Deltas: {derror}')

Iter: 0
Prediction: [0.555 0.98  0.965]
Error: [2.07025e-01 4.00000e-04 7.48225e-01]
Delta: [ 0.455 -0.02   0.865]
Weights: [[ 6.1325000e-02  9.7042500e-02 -3.0546000e-01]
 [ 1.0170000e-01  2.0013000e-01  2.4000000e-04]
 [-7.3525000e-02  1.2943775e+00  8.9620000e-02]]
Weight Deltas: [[ 3.8675   0.29575  0.546  ]
 [-0.17    -0.013   -0.024  ]
 [ 7.3525   0.56225  1.038  ]]
Iter: 1
Prediction: [0.21778812 0.9948225  0.32392687]
Error: [1.38740424e-02 2.68065063e-05 5.01432453e-02]
Delta: [ 0.11778812 -0.0051775   0.22392687]
Weights: [[ 5.13130094e-02  9.62768772e-02 -3.06873458e-01]
 [ 1.02140088e-01  2.00163654e-01  3.02130000e-04]
 [-9.25587844e-02  1.29292198e+00  8.69328775e-02]]
Weight Deltas: [[ 1.00119906  0.07656228  0.14134575]
 [-0.04400875 -0.00336538 -0.006213  ]
 [ 1.90337844  0.14555247  0.26871225]]
Iter: 2
Prediction: [0.1304924  0.99865967 0.15796907]
Error: [9.29786510e-04 1.79647194e-06 3.36041305e-03]
Delta: [ 0.0304924  -0.00134033  0.05796907]
Weights: [[ 4.8721155