### 1. Neural network with only one input

In [14]:
weight = 0.1
def neural_network(input, weight):
    prediction = input * weight
    return prediction

In [15]:
number_of_toes = [8.5, 9.5, 10, 9]
input = number_of_toes[0]
pred = neural_network(input, weight)
print(pred)

0.8500000000000001


Auxiliary task -- scalar product using `elementwise_multiplication(vec_a, vec_b)` and `vector_sum(vec_a)` functions

In [16]:
def elementwise_multiplication(vec_a, vec_b):
    assert(len(vec_a) == len(vec_b))
    output = []
    for i in range(len(vec_a)):
        output.append(vec_a[i] * vec_b[i])
    return output

In [17]:
def vector_sum(vec_a):
    output = 0;
    for i in range(len(vec_a)):
        output += vec_a[i]
    return output

In [18]:
def w_sum(a, b):
    return vector_sum(elementwise_multiplication(a, b))

### 2. Neural network with multiple inputs

In [19]:
weights = [0.1, 0.2, 0.0]
def neural_network(input, weights):
    pred = w_sum(input, weights)
    return pred

In [20]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]
pred = neural_network(input, weights)
print(pred)

0.9800000000000001


### 3. Neural network with multiple inputs (NumPy)

In [21]:
import numpy as np
weights = np.array([0.1, 0.2, 0.0])
def neural_network(input, weights):
    return input.dot(weights)

In [22]:
toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])
pred = neural_network(input, weights)
print(pred)

0.9800000000000001


### 4. Neural network with single input and multiple outputs

In [23]:
def ele_mul(number, vector):
    output = []
    for i in range(len(vector)):
        output.append(number * vector[i])
    return output

In [24]:
weights = [0.3, 0.2, 0.9]
def neural_network(input, weights):
    return ele_mul(input, weights)

In [25]:
wlrec = [0.65, 0.8, 0.8, 0.9]
input = wlrec[0]
pred = neural_network(input, weights)
print(pred)

[0.195, 0.13, 0.5850000000000001]


### 5. Neural network with multiple inputs and outputs

In [26]:
def vect_mat_mul(vect, matrix):
    output = []
    for i in range(len(vect)):
        output.append(w_sum(vect, matrix[i]))
    return output

In [31]:
weights = [[0.1, 0.1, -0.3], # injury 
          [0.1, 0.2, 0.0],   # victory
          [0.0, 1.3, 0.1]]   # sadness
def neural_network(input, weights):
    return vect_mat_mul(input, weights)

In [32]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]
pred = neural_network(input, weights)
print(pred)

[0.555, 0.9800000000000001, 0.9650000000000001]


### 6. Neural network with hidden layer

In [38]:
ih_wgt = [[0.1,  0.2, -0.1], 
          [-0.1, 0.1, 0.9],
          [0.1,  0.4, 0.1]]
hp_wgt = [[0.3, 1.1, -0.3],
          [0.1, 0.2, 0.0], 
          [0.0, 1.3, 0.1]]
weights = [ih_wgt, hp_wgt]
def neural_network(input, weights):
    hid = vect_mat_mul(input, weights[0])
    return vect_mat_mul(hid, weights[1])

In [39]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]
pred = neural_network(input, weights)
print(pred)

[0.21350000000000002, 0.14500000000000002, 0.5065]


### 7. Neural network with hidden layer (NumPy)

In [40]:
import numpy as np
ih_wgt = np.array([[0.1,  0.2, -0.1], 
                   [-0.1, 0.1, 0.9],
                   [0.1,  0.4, 0.1]]).T
hp_wgt = np.array([[0.3, 1.1, -0.3],
                   [0.1, 0.2, 0.0], 
                   [0.0, 1.3, 0.1]]).T
weights = [ih_wgt, hp_wgt]
def neural_network(input, weights):
    return input.dot(weights[0]).dot(weights[1])

In [41]:
toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])
pred = neural_network(input, weights)
print(pred)

[0.2135 0.145  0.5065]


### 8. NumPy detour

In [44]:
import numpy as np

a = np.array([0, 1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([[0, 1, 2, 3], 
              [4, 5, 6, 7]])
d = np.zeros((2, 4))
e = np.random.rand(2, 5)

print(a)
print(b)
print(c)
print(d)
print(e)

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.94080465 0.61251313 0.17351697 0.09298302 0.92529067]
 [0.22092187 0.48540955 0.59821351 0.37204712 0.69078894]]


In [46]:
print(a * 0.1)
print(c * 0.2)
print(a * b)
print(a * b * 0.2)
print(a * c)

print(a * e) ## Should raise an error due to shape problems

[0.  0.1 0.2 0.3]
[[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]]
[ 0  5 12 21]
[0.  1.  2.4 4.2]
[[ 0  1  4  9]
 [ 0  5 12 21]]


ValueError: operands could not be broadcast together with shapes (4,) (2,5) 

In [47]:
a = np.zeros((1, 4))
b = np.zeros((4, 3))

c = a.dot(b)
print(c.shape)

(1, 3)


In [49]:
a = np.zeros((2, 4))
b = np.zeros((4, 3))

c = a.dot(b)
print(c.shape)

(2, 3)


In [51]:
e = np.zeros((2, 1))
f = np.zeros((1, 3))

g = e.dot(f)
print(g.shape)

(2, 3)


In [52]:
h = np.zeros((5, 4)).T
i = np.zeros((5, 6))

j = h.dot(i)
print(j.shape)

(4, 6)


In [54]:
h = np.zeos((5, 4))
i = np.zeos((5, 6))

j = h.dot(i) ## Should raise an error due to shape problems
print(j)

AttributeError: module 'numpy' has no attribute 'zeos'